---
image:
    file: .gitpod/Dockerfile
    context: .gitpod
checkoutLocation: gopherbot
workspaceLocation: "."
tasks:
- before: make -C gopherbot
- init: cp -a ./gopherbot/.gitpod/*.theia-workspace /workspace
- init: ./gopherbot/.gitpod/gotools.sh
- command: ./gopherbot/.gitpod/setup.sh
  openIn: main
ports:
- port: 8080
  onOpen: ignore
